# Generated by Django 2.2.7 on 2019-11-30 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
