# Generated by Django 2.2.7 on 2019-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191130_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createdAt',
            field=models.DateTimeField(default='2019-11-30 17:30:43'),
        ),
    ]
