# Generated by Django 2.2.7 on 2019-11-30 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191130_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
