# Generated by Django 2.2.7 on 2019-11-30 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191130_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
